INSERT INTO categories (description, `type`, `mode`, `order`, tournament_id)
VALUES ('PRUEBA DE MENORES','selection','personal',1,6),
('PRUEBA DE ENFRENADURA','selection','personal',2,6),
('BURROS HECHORES','selection','personal',3,6),
('MULARES','selection','personal',4,6),
('CONJUNTO DE MULARES','selection','personal',5,6),
('POTROS MULETEROS','selection','personal',6,6),
('CATEGORIA DE POTRANCAS AL CABESTRO DE 1 A 3 AÑOS - GRUPO 1','selection','personal',7,6),
('CATEGORIA DE POTRANCAS AL CABESTRO DE 1 A 3 AÑOS - GRUPO 2','selection','personal',8,6),
('CATEGORIA DE POTRANCAS AL CABESTRO DE 1 A 3 AÑOS - GRUPO 3','selection','personal',9,6),
('CATEGORIA DE POTRANCAS AL CABESTRO DE 1 A 3 AÑOS - GRUPO 4','selection','personal',10,6),
('CATEGORIA DE POTRANCAS DE BOZAL DE 3 A 4 AÑOS - GRUPO 1','selection','personal',11,6),
('CATEGORIA DE POTRANCAS DE BOZAL DE 3 A 4 AÑOS - GRUPO 2','selection','personal',12,6),
('CATEGORIA DE POTRANCAS DE BOZAL DE 3 A 4 AÑOS - GRUPO 3','selection','personal',13,6),
('CATEGORIA DE POTRANCAS DE BOZAL DE 3 A 4 AÑOS - GRUPO 4','selection','personal',14,6),
('CATEGORIA DE YEGUAS DE FRENO Y ESPUELAS DE MAS DE 4 AÑOS - GRUPO 1','selection','personal',15,6),
('CATEGORIA DE YEGUAS DE FRENO Y ESPUELAS DE MAS DE 4 AÑOS - GRUPO 2','selection','personal',16,6),
('CATEGORIA DE YEGUAS DE FRENO Y ESPUELAS DE MAS DE 4 AÑOS - GRUPO 3','selection','personal',17,6),
('CATEGORIA DE YEGUAS DE FRENO Y ESPUELAS DE MAS DE 4 AÑOS - GRUPO 4','selection','personal',18,6),
('CATEGORIA DE YEGUAS DE FRENO Y ESPUELAS DE MAS DE 4 AÑOS - GRUPO 5','selection','personal',19,6),
('CATEGORIA DE YEGUAS DE FRENO Y ESPUELAS DE MAS DE 4 AÑOS - GRUPO 6','selection','personal',20,6),
('CATEGORIA DE YEGUAS DE FRENO Y ESPUELAS DE MAS DE 4 AÑOS - GRUPO 7','selection','personal',21,6),
('CATEGORIA DE YEGUAS DE FRENO Y ESPUELAS DE MAS DE 4 AÑOS - GRUPO 8','selection','personal',22,6),
('CATEGORIA DE YEGUAS DE FRENO Y ESPUELAS DE MAS DE 4 AÑOS - GRUPO 9','selection','personal',23,6),
('CATEGORIA DE YEGUAS DE FRENO Y ESPUELAS DE MAS DE 4 AÑOS - GRUPO 10','selection','personal',24,6),
('PREMIO PISOS PARA YEGUAS','selection','personal',25,6),
('PREMIO PROGENIE DE MADRE','selection','group',26,6),
('PREMIO MADRE E HIJA','selection','group',27,6),
('PREMIO CONJUNTO DE YEGUAS','selection','group',28,6),
('PREMIO MERITO ZOOTECNICO HEMBRA','selection','personal',29,6),
('CATEGORIA DE POTRILLOS AL CABESTRO DE 1 A 3 AÑOS - GRUPO 1','selection','personal',30,6),
('CATEGORIA DE POTRILLOS AL CABESTRO DE 1 A 3 AÑOS - GRUPO 2','selection','personal',31,6),
('CATEGORIA DE POTRILLOS AL CABESTRO DE 1 A 3 AÑOS - GRUPO 3','selection','personal',32,6),
('CATEGORIA DE POTRILLOS DE BOZAL DE 3 A 4 AÑOS - GRUPO 1','selection','personal',33,6),
('CATEGORIA DE POTRILLOS DE BOZAL DE 3 A 4 AÑOS - GRUPO 2','selection','personal',34,6),
('CATEGORIA DE POTROS DE FRENO Y ESPUELAS DE MAS DE 4 AÑOS - GRUPO 1','selection','personal',35,6),
('CATEGORIA DE POTROS DE FRENO Y ESPUELAS DE MAS DE 4 AÑOS - GRUPO 2','selection','personal',36,6),
('CATEGORIA DE POTROS DE FRENO Y ESPUELAS DE MAS DE 4 AÑOS - GRUPO 3','selection','personal',37,6),
('CATEGORIA DE POTROS DE FRENO Y ESPUELAS DE MAS DE 4 AÑOS - GRUPO 4','selection','personal',38,6),
('PREMIO PISOS PARA POTROS','selection','personal',39,6),
('PREMIO PROGENIE DE PADRE','selection','personal',40,6),
('PREMIO CONJUNTO DE POTROS','selection','group',41,6),
('PREMIO MERITO ZOOTECNICO MACHO','selection','personal',42,6),
('CATEGORIA DE CAPONES DE BOZAL DE 3 A 4 AÑOS','selection','personal',43,6),
('CATEGORIA DE CAPONES DE FRENO Y ESPUELAS DE MAS DE 4 AÑOS - GRUPO 1','selection','personal',44,6),
('CATEGORIA DE CAPONES DE FRENO Y ESPUELAS DE MAS DE 4 AÑOS - GRUPO 2','selection','personal',45,6),
('CATEGORIA DE CAPONES DE FRENO Y ESPUELAS DE MAS DE 4 AÑOS - GRUPO 3','selection','personal',46,6),
('PREMIO PISOS PARA CAPONES','selection','personal',47,6),
('PREMIO CONJUNTO DE CAPONES','selection','group',48,6),
('CAMPEON BOZAL CAPON','selection','personal',49,6),
('PREMIO A LA MEJOR POTRANCA PRESENTADA AL CABESTRO','selection','personal',50,6),
('PREMIO AL MEJOR POTRILLO PRESENTADO AL CABESTRO','selection','personal',51,6),
('CAMPEONA BOZAL HEMBRA','selection','personal',52,6),
('CAMPEON BOZAL MACHO','selection','personal',53,6),
('TRES GENERACIONES','selection','personal',54,6),
('CAMPEON Y RESERVA DE CAMPEON DEL AÑO CAPON','selection','personal',55,6),
('CAMPEONA Y RESERVA DE CAMPEONA DEL AÑO HEMBRA','selection','personal',56,6),
('CAMPEON Y RESERVA DE CAMPEON DEL AÑO MACHO','selection','personal',57,6),
('PREMIO AFICION','selection','group',58,6),
('CAMPEON DE CAMPEONES CAPON','selection','personal',59,6),
('CAMPEONA DE CAMPEONAS HEMBRA','selection','personal',60,6),
('CAMPEON DE CAMPEONES MACHO','selection','personal',61,6)
